Update default message
readthedocs-fr/bin-server pull request #115
Opened 2021-02-27 20:34 UTC by zazbone

Proposition de message d'acceuil
Non testé

2021-02-27 22:14 UTC, Julien00859 commented
Hello @zazbone

Merci pour cette première contribution, cependant j'ai peur de constaté que tu n'as pas pris connaissance de nos méthodes de collaboration :(

Le nom de la branche doit contenir quelques mots clés (séparé par des -) suivi d'un diminutif pour ton pseudo. Pour ta branche, je peux te suggérer "placeholder-documentation-zaz".

Comme tout ce qu'il restera des discussions sur discord, sur l'issue et sur la pull request sera le code et le message de commit, nous mettons une attention toute particulière à rédiger un message de commit complet sous la force suivantes:

	type: titre sur 50 caractères maximum

	Plusieurs paragraphe pour documenter les changements, maximum 80 caractères par
	ligne.

	Une section (ou un paragraphe) expliquant *pourquoi* les changements que tu
	proposes sont nécessaires. Normalement tu reprends ici avec tes mots le problème
	qui a déjà été énoncé dans l'issue.

	Une section (ou un paragraphe) optionnel pour apporter une considération
	technique, tu reprends ici différents problèmes ou considérations techniques,
	est-ce qu'il y avait plusieurs solutions techniques possibles, quels étaient les
	avantages et inconvéniants de chacune.

	Une section (ou un paragraphe) optionnel pour expliquer le code directement, si
	il y a quelque chose qui sort de l'ordinaire et qui justifie d'être documenter.

Le type peut être soit `doc` (documentation), `fix` (correctif de bug), `add` (ajout d'une nouvelle fonctionnalité), `ref` (réecriture importante d'une fonctionnalité existante), `rel` (nouvelle version), `imp` (amélioration d'une fonctionnalité existante ou ajout mineur).

Pour ce commit, je suggère le message suivant:

	imp: use newform placeholder as howto use doc

	It appears some newbies don't know what to do when they land on the /index.html
	front page of bin. We are talking about the kind of newbie that share their
	code by taking a camera picture of their screen, typical John-script-kiddie
	who learn to code during summer break with youtube tutorials.

	In order they figure out themselves how to use bin, a user documentation is now
	shown via the textarea placeholder. Instead of "paste your code here" there is
	a more complete tutorial explaing what a pastebin service is and how to use one.

	Closes #114

Aussi je lis dans ta pull-request que tu n'as pas testé le code, j'espère que tu comprends qu'on ne va pas merger un bout de code que son auteur n'a même pas pris la peine de tester. Est-ce que tu as eu des problèmes pour le tester ? On peut peut-être t'aider :)

Pour en arriver au code en lui-même, je ne suis pas vraiment favorable à le merger dans l'état. Je pense que mettre le texte dans une fichier à part et le charger comme un template bottle serait mieux. Avec un fichier à part, si quelqu'un veut changer le texte, tout ce qu'il aura à faire sera de changer un fichier txt, même le dernier des abrutis en sera capable. Dans l'état actuel il faut au moins comprendre que c'est une jointure de string.

2021-02-27 22:18 UTC, Julien00859 commented
Aussi, je suis vraiment désolé que ça tombe sur toi, nous avons fait une fausse manip sur github et nous avons été forcé de réécrire l'historique de la branche main. Branche que tu avais déjà récupéré en local chez toi. Pour nous permettre de t'aider à également corriger le problème chez toi, veux-tu bien nous indiquer comment est-ce que tu as contribué au projet ? Via un fork et le bouton "edit" disponible dans l'interface de github ? Via un fork, un clone sur ta machine et une nouvelle branche en local ?

2021-02-27 22:36 UTC, zazbone commented
Ok je vois pas de soucis c'est ma faute

Le fork a été créé via l'edit direct sur github
Ca sera sans doute plus rapide de la supprimer et de partir sur un clone local :thinking:

Pour le fichier du coup j'ai testé le syntaxe `include` mais j'imagine qu'elle fonctionne pas si simplement dans une balise, j'ai que la commande qui s'affiche sur le bin en local

2021-02-27 23:27 UTC, Julien00859 commented
Pour `% include` il faut lancer le serveur, c'est une directive du moteur de templating de bottle. https://bottlepy.org/docs/dev/stpl.html?highlight=include#stpl.include

Sinon oui je pense que ce sera mieux de fork et cloner en  local :)

2021-03-06 16:44 UTC, Julien00859 requested changes
Message plus haut

2021-04-14 17:35 UTC, Mesteery commented
(@zazbone)

2021-05-07 18:48 UTC, Mesteery commented on bin/views/howto.txt
> +Merci d'utiliser ce bin !\\
je pense que ça pourrait être mieux formuler

2021-05-08 12:56 UTC, zazbone commented
J'avais écrit ça il y a quelque temps 
> Bonjour!

> Pour partager votre code, copiez collez le ici ou glissez un fichier
> Cliquez sur l'icone bleu en bas à droite: "enregistrer"
> Finalement, copiez et partager le lien de la page

> Attention! Le bin ne concervera pas durablement le code

> Merci d'utiliser ce bin!

J'ai pas pris le temps de comprendre pourquoi j'arrivais pas à pr mon commit en local
Donc j'ai un howto.txt qui attend 'être commit

2021-05-08 12:57 UTC, Mesteery commented
oups, sorry, j'avais remarquer que cette PR trainait trop, et que après plusieurs relances y avait plus de réponse. Donc hier, je l'ai reprise.

2021-11-15 15:22 UTC, Julien00859 approved these changes

2021-11-15 17:31 UTC, Mesteery approved these changes

2021-11-19 16:25 UTC, merged