110 logging juc
readthedocs-fr/bin-server pull request #130
Opened 2021-04-01 01:36 UTC by Julien00859

2021-04-01 01:36 UTC, Julien00859 commented
cc #110

2021-04-01 01:40 UTC, Julien00859 reviewed
IL EST PRESQUE 4H ET TU AS FAIT QUE ÇA MAIS WTF

2021-04-01 01:40 UTC, Julien00859 commented on bin/assets/styles/style.css
> +div.controls {
arrêter de pisser tu veux, connard, sombre merde, LIS TES PUTAIN DE DIFF AVANT DE COMMIT

2021-04-01 01:40 UTC, Julien00859 commented on bin/views/head.html
> +<meta name=description content="https://github.com/readthedocs-fr/bin-server">
Qu'est-ce que ça fou dans cette PR ?

2021-04-01 01:40 UTC, Julien00859 commented on bin/assets/scripts/report.js
> +});
Rigolo ce code de merde, surtout qu'il marche pas

2021-04-01 01:40 UTC, Julien00859 commented on bin/config.py
> +import logging
encore faudrait-il qu'il log qqch MERCI GUNICORN DE MERDE

2021-04-01 01:40 UTC, Julien00859 commented on bin/controller.py
> +    logger.info("New %s snippet: %s", lang, snippet.id)
Rigolo, voila 2 mois que j'ai ça en prod, oui je modifie le code source en prod comme un crado

2021-04-01 05:23 UTC, Mesteery commented
On n'avait pas dit qu'on restait séreux ici ? :kappa:

2021-04-01 05:24 UTC, Mesteery commented on bin/assets/scripts/report.js
> +});
Il est moche ton code, tu ne respecte même pas le code style habituel...

2021-04-02 09:44 UTC, Julien00859 commented on bin/assets/scripts/report.js
> +});
Comment il faudrait faire ??

2021-04-02 12:52 UTC, Julien00859 commented on bin/views/head.html
> +<meta name=description content="https://github.com/readthedocs-fr/bin-server">
Héhé petit commit à part en furt :eyes:

2021-04-02 17:54 UTC, Mesteery requested changes

2021-04-02 17:54 UTC, Mesteery commented on bin/assets/scripts/report.js
> +      "Vous allez signaler ce snippet auprès de l'administrateur.\n"
Pas besoin de parenthèses. De plus, renseigne toi sur les *template literals*

2021-04-02 17:54 UTC, Mesteery commented on bin/assets/scripts/report.js
> +const reportForm = document.forms['report'];
```suggestion
const reportForm = document.forms.report;

```

2021-04-02 17:54 UTC, Mesteery commented on bin/assets/scripts/report.js
> +    const name = prompt(promptMessage).trim();
Il faut vérifier si l'utilisateur à entrer quelque chose et que s'il entré quelque chose que la longeur  soit > 0 (ou autre limite)

2021-04-02 17:54 UTC, Mesteery commented on bin/assets/scripts/report.js
> +    return name.length;
return inutile

2021-04-02 17:54 UTC, Mesteery commented on bin/assets/styles/report.css
> +form#report {
Pour être consistent avec le reste enleve `form` et `.5` -> `0.5`.

Sinon je comprend pas pourquoi tu position absolute et display none input

2021-04-02 17:54 UTC, Mesteery commented on bin/config.py
> +def _setup():
Pourquoi faire une fonction ?
Sinon pourquoi préfixer avec un _ ?

2021-04-02 18:12 UTC, Julien00859 commented on bin/assets/scripts/report.js
> +    return name.length;
dans un submit il est utile, la fonction doit renvoyer true ou false si il faut propager le submit ou pas

2021-04-02 18:13 UTC, Julien00859 commented on bin/assets/scripts/report.js
> +    const name = prompt(promptMessage).trim();
si l'utilisateur est en noscript, alors il ne pourra de toute façon rien rentrer, j'ai préféré rester cohérant et les laisser ne pas mettre de nom (puis ça plantera niveau backend)

2021-04-02 18:13 UTC, Mesteery commented on bin/assets/scripts/report.js
> +    return name.length;
Il se propagera sans problème tant qu'on `preventDefault` pas

2021-04-02 18:15 UTC, Mesteery commented on bin/assets/scripts/report.js
> +    const name = prompt(promptMessage).trim();
Oui mais là ton code peut ne pas fonctionner (prompt peut renvoyer undefined) et puis rien ne coûte à vérifier la longueur avant d'envoyer

2021-04-02 18:15 UTC, Julien00859 commented on bin/assets/scripts/report.js
> +      "Vous allez signaler ce snippet auprès de l'administrateur.\n"
Je connais et c'est pas beau

2021-04-02 18:15 UTC, Julien00859 commented on bin/config.py
> +def _setup():
C'est marqué dans le message de commit

2021-04-02 18:16 UTC, Julien00859 commented on bin/assets/scripts/report.js
> +    const name = prompt(promptMessage).trim();
puis, cf mon message en dessous, ça ne submit pas quand le champ est laissé vide

2021-04-02 18:16 UTC, Mesteery commented on bin/assets/scripts/report.js
> +      "Vous allez signaler ce snippet auprès de l'administrateur.\n"
Si ça l'est..., bien plus que cette horreur

2021-04-02 18:17 UTC, Julien00859 commented on bin/assets/styles/report.css
> +form#report {
Je trouve ça dommage qu'on ne laisse que l'id, tu perds l'info sur quel type d'élément tu es en train de styliser

2021-04-02 18:19 UTC, Mesteery commented on bin/assets/styles/report.css
> +form#report {
Bah bof, à part avoir Alzheimer je pense qu'on est capable de quoi s'agit-il, surtout que le form est inutile et presque redondant

2021-04-02 18:25 UTC, Mesteery commented on bin/assets/scripts/report.js
> +    const name = prompt(promptMessage).trim();
Bah si, et ça laissera une erreur : `undefined.lenght`...

2021-04-02 18:29 UTC, Julien00859 commented on bin/assets/scripts/report.js
> +    return name.length;
Dingue ça, ça a changé depuis la dernière fois que j'ai fait du JS, je corrige ça

2021-04-02 19:43 UTC, Mesteery commented on bin/views/head.html
> +<meta name=description content="https://github.com/readthedocs-fr/bin-server">
Mais du coup pourquoi ce changement ?

2021-04-06 23:05 UTC, Mesteery requested changes

2021-04-06 23:05 UTC, Mesteery commented on bin/views/highlight.html
> +        <script src="/assets/scripts/report.js" defer></script>
Est-vraiment nécessaire d'ajouter des fichiers supplémentaires à charger ? Je pense que `loc.js` et `report.js` pourraient fusionnés et le fichier final pourrait être renommé.
*Vivement #55*

2021-04-06 23:05 UTC, Mesteery commented on bin/assets/styles/report.css
> +	width: 1em;
```suggestion
	width: 1.5em;
```
c'était un peu trop petit

2021-04-06 23:05 UTC, Mesteery commented on bin/views/highlight.html
> +        <form id=report name=report action="/report" method=POST>
```suggestion
        <form id=report title="Signaler" name=report action="/report" method=POST>
```

2021-04-06 23:05 UTC, Mesteery commented on bin/assets/styles/report.css
> +
```suggestion

#report label {
	cursor: pointer;
}

```

2021-04-07 09:30 UTC, Mesteery approved these changes

2021-04-10 17:32 UTC, NoeXWolf reviewed
Je trouve ça un peu brouillon de simplement return une `HTTPResponse` à la fin du report.
Je verrais à la place un `alert("The snippet have been reported.")` côté js et ensuite un redirect sur `/` ou sur le snippet.

2021-04-10 17:32 UTC, NoeXWolf commented on bin/assets/scripts/report.js
> +  reportForm.name.value = name;
```suggestion
  reportForm.name.value = name;
  alert("The snippet have been reported.");
```

2021-04-10 17:32 UTC, NoeXWolf commented on bin/controller.py
> +    return bt.HTTPResponse("The snippet have been reported.")
```suggestion
    bt.redirect('/')
```
ou
```suggestion
    bt.redirect(f'/{snippetid}')
```
(Il faudrait dans ce deuxième cas gérer l'extension via le formulaire).

2021-04-10 17:36 UTC, Mesteery commented
Sauf que non, car :
1. On a aucune garantie de la réussite du report
2. La gestion de l'affichage des erreurs compliquerait tout (chose, qui d'ailleurs bloque complètement #116)

2021-04-10 17:40 UTC, NoeXWolf commented
Je trouve aussi que le bouton pour report est trop petit et trop discret, même s'il n'est pas censé être utilisé souvent il faut que l'utilisateur sache qu'il existe. J'ai pensé qu'on pouvait le mettre dans le même style que les autres boutons mais avec un fond rouge ou quelque chose dans le genre, mais bon je suis pas dev frontend alors je vais pas proposer de code sinon ça va être l'anarchie.
Si vous voulez le laisser comme ça, au moins le passer à 2em et augmenter un peu les margins (top et right à 1em) ça ne coûte rien et ça fait pas juste une petite crotte collée dans le coin ;)

2021-04-10 17:43 UTC, Mesteery commented
> Je trouve aussi que le bouton pour report est trop petit et trop discret, même s'il n'est pas censé être utilisé souvent il faut que l'utilisateur sache qu'il existe. J'ai pensé qu'on pouvait le mettre dans le même style que les autres boutons mais avec un fond rouge ou quelque chose dans le genre, mais bon je suis pas dev frontend alors je vais pas proposer de code sinon ça va être l'anarchie.
> Si vous voulez le laisser comme ça, au moins le passer à 2em et augmenter un peu les margins (top et right à 1em) ça ne coûte rien et ça fait pas juste une petite crotte collée dans le coin ;)

Ça j'ai testé, sur PC et téléphone, de base c'était légèrement petit (1em) j'ai donc suggéré 1.5em qui était la parfaite valeur entre 1 et 2.
Ce qui est bien, ce que l'icone est parfaitement intégrer à l'UI, c'est pas très discret pour autant. 
J'ai aussi essayer d'augmenter la marge mais c'était vraiment pas terrible (surtout sur des appareils de petite taille).
Perso je trouve qu'actuellement c'est parfait.

2021-04-10 17:46 UTC, NoeXWolf commented
> > Je trouve aussi que le bouton pour report est trop petit et trop discret, même s'il n'est pas censé être utilisé souvent il faut que l'utilisateur sache qu'il existe. J'ai pensé qu'on pouvait le mettre dans le même style que les autres boutons mais avec un fond rouge ou quelque chose dans le genre, mais bon je suis pas dev frontend alors je vais pas proposer de code sinon ça va être l'anarchie.
> > Si vous voulez le laisser comme ça, au moins le passer à 2em et augmenter un peu les margins (top et right à 1em) ça ne coûte rien et ça fait pas juste une petite crotte collée dans le coin ;)
> 
> Ça j'ai testé, sur PC et téléphone, de base c'était légèrement petit (1em) j'ai donc suggéré 1.5em qui était la parfaite valeur entre 1 et 2.
> Ce qui est bien, ce que l'icone est parfaitement intégrer à l'UI, c'est pas très discret pour autant.
> J'ai aussi essayer d'augmenter la marge mais c'était vraiment pas terrible (surtout sur des appareils de petite taille).
> Perso je trouve qu'actuellement c'est parfait.

J'ai pas moyen de tester sur tel alors je te fais confiance.
Si c'est parfait pour vous alors c'est parfait pour moi.

2021-04-10 17:48 UTC, Mesteery commented
> > > Je trouve aussi que le bouton pour report est trop petit et trop discret, même s'il n'est pas censé être utilisé souvent il faut que l'utilisateur sache qu'il existe. J'ai pensé qu'on pouvait le mettre dans le même style que les autres boutons mais avec un fond rouge ou quelque chose dans le genre, mais bon je suis pas dev frontend alors je vais pas proposer de code sinon ça va être l'anarchie.
> > > Si vous voulez le laisser comme ça, au moins le passer à 2em et augmenter un peu les margins (top et right à 1em) ça ne coûte rien et ça fait pas juste une petite crotte collée dans le coin ;)
> > 
> > 
> > Ça j'ai testé, sur PC et téléphone, de base c'était légèrement petit (1em) j'ai donc suggéré 1.5em qui était la parfaite valeur entre 1 et 2.
> > Ce qui est bien, ce que l'icone est parfaitement intégrer à l'UI, c'est pas très discret pour autant.
> > J'ai aussi essayer d'augmenter la marge mais c'était vraiment pas terrible (surtout sur des appareils de petite taille).
> > Perso je trouve qu'actuellement c'est parfait.
> 
> J'ai pas moyen de tester sur tel alors je te fais confiance.
> Si c'est parfait pour vous alors c'est parfait pour moi.

Je peux envoyer des screen si tu veux.

2021-04-10 17:50 UTC, NoeXWolf commented
> Je peux envoyer des screens si tu veux.

Je veux bien.

2021-04-10 17:50 UTC, NoeXWolf commented
> Sauf que non, car :
> 
> 1. On a aucune garantie de la réussite du report
> 2. La gestion de l'affichage des erreurs compliquerait tout (chose qui d'ailleurs bloque complètement #116)

Dans ce cas est-ce que ça vaudrait le coup de faire une page indépendante pour ça ?
Parce que bon c'est quand même un peu naze un texte noir sur blanc en police times new roman taille 16.

2021-04-10 17:53 UTC, Mesteery commented
(La police n'est pas défini, elle dépend de l'utilisateur)
Perso ça me gêne pas. Après, si tu trouves un moyen de correctement afficher les erreurs et garantir le succès du signalement au client ce serait pas mal

2021-04-11 15:34 UTC, NoeXWolf approved these changes

2021-04-11 20:02 UTC, merged