[ADD] Make snippets have a max number of views
readthedocs-fr/bin-server pull request #27
Opened 2020-10-31 16:48 UTC by NoeXWolf

```
The user is now able to set a maximum number of views/uses on his
snippets. By default, this number is infinite. The user can turn off the
infinite views by unchecking the 'infinite_views checkbox and by
entering a views number in the 'max_views' input field (it has to be a
number greater than 0). Every time the snippet's page is visited, its
views left decrease, and when it gets to 0, the snippet is deleted from
the database.
```

2020-10-31 17:04 UTC, Julien00859 requested changes
L'historique est foireux... Très moche commit de merge...

2020-10-31 17:04 UTC, Julien00859 commented on bin/controller.py
> +    max_views = math.inf
float('+inf'), l'import à `math` n'est plus nécessaire

2020-10-31 17:04 UTC, Julien00859 commented on bin/controller.py
> +                raise bt.HTTPError(422, 'Max views should be greater than 0')                   # TODO: error handling in front-side
Le code d'erreur 422 est une extension WebDAV, on ne fait pas de WebDAV ici. Il faut utiliser 400.

2020-10-31 17:04 UTC, Julien00859 commented on bin/controller.py
> +            raise bt.HTTPError(422, f"Max views '{forms.get('max_views')}' is not a number")    # TODO: error handling in front-side
HTTP Code 400

2020-10-31 17:04 UTC, Julien00859 commented on bin/models.py
> +                database.hset(snippet_id, 'views_left', int(views_left))
Use `HINCRBY` https://redis.io/commands/hincrby

2020-10-31 17:04 UTC, Julien00859 commented on bin/models.py
> +            return cls.db[ident]
Pour rester consistant avec redis, `cls.db.get`

2020-10-31 17:04 UTC, Julien00859 commented on bin/models.py
> +import math
L'import n'est pas utilisé

2020-10-31 17:04 UTC, Julien00859 commented on bin/controller.py
> +        code = forms.get('code', '').encode('latin-1')
Attention auteurs de #26 ce changement va rentrer en conflit.

2020-10-31 17:08 UTC, fusetim commented
J'ai l'impression que le paramètre est obligatoire, il serait mieux de le garder optionnel (avec une valeur par défaut) pour éviter au personne n'utilisant pas l'interface web de devoir remplir tous ces champs.

2020-10-31 17:11 UTC, fusetim commented on bin/controller.py
> +            max_views = int(forms.get('max_views'))
Il serait bien d'utiliser une valeur par défaut ici (comme +infini)
```suggestion
            max_views = int(forms.get('max_views', '+inf'))
```

2020-10-31 17:15 UTC, Julien00859 commented
Ne fonctionne pas lorsqu'on publie un bin en multi-part.

Reproduire via curl:

    echo Hello | curl -F file=@- http://localhost:8012/new

Traceback:

    Traceback (most recent call last):
      File "/home/julien/Projects/bin/venv/lib/python3.8/site-packages/bottle.py", line 868, in _handle
        return route.call(**args)
      File "/home/julien/Projects/bin/venv/lib/python3.8/site-packages/bottle.py", line 1748, in wrapper
        rv = callback(*a, **ka)
      File "/home/julien/Projects/bin/bin/controller.py", line 63, in post_new
        max_views = int(forms.get('max_views'))
    TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
    127.0.0.1 - - [31/Oct/2020 18:13:30] "POST /new HTTP/1.1" 500 1532

2020-10-31 17:19 UTC, Julien00859 commented on bin/controller.py
> +            max_views = int(forms.get('max_views'))
Il faut utiliser `float`, `+inf` n'est pas un entier valide

2020-10-31 17:25 UTC, NoeXWolf commented on bin/controller.py
> +            max_views = int(forms.get('max_views'))
La valeur par défaut est déjà en haut : `max_views = math.inf`. Je changerai pour `float('+inf')` comme à dit lazor plus tard

2020-10-31 17:26 UTC, NoeXWolf commented
Je ferai les modifs plus tard, j'ai eu ma dose là.

2020-10-31 17:26 UTC, fusetim commented on bin/controller.py
> +            max_views = int(forms.get('max_views'))
Malheureusement `forms.get("max_view")` peut renvoyer None; et donc max_view sera None

2020-10-31 22:17 UTC, NoeXWolf commented on bin/controller.py
> +            max_views = int(forms.get('max_views'))
Ah j'ai oublié de changer ça...

2020-11-01 14:52 UTC, fusetim commented
Il semblerait que quelque chose ait cassé, quelque soit la valeur donnée sur la version web, j'ai une erreur 500.

Options serveur:
```REDIS_ENABLED=false```

Traceback:
```
Traceback (most recent call last):
  File "/mnt/storagedisk/Developing/IntelliJ/read_the_docs_fr/bin/venv/lib/python3.8/site-packages/bottle.py", line 868, in _handle
    return route.call(**args)
  File "/mnt/storagedisk/Developing/IntelliJ/read_the_docs_fr/bin/venv/lib/python3.8/site-packages/bottle.py", line 1748, in wrapper
    rv = callback(*a, **ka)
  File "/mnt/storagedisk/Developing/IntelliJ/read_the_docs_fr/bin/bin/controller.py", line 49, in post_new
    snippet = Snippet.create(code.decode('utf-8'), max_views)
  File "/mnt/storagedisk/Developing/IntelliJ/read_the_docs_fr/bin/bin/models.py", line 40, in create
    database.hset(ident, "views_left", views_left)
  File "/mnt/storagedisk/Developing/IntelliJ/read_the_docs_fr/bin/bin/models.py", line 19, in hset
    cls.db.get(ident)[field] = value.encode()
AttributeError: 'float' object has no attribute 'encode'
127.0.0.1 - - [01/Nov/2020 15:49:37] "POST /new HTTP/1.1" 500 1923
```

2020-11-01 15:12 UTC, NoeXWolf commented
Je pense qu'il faudra enlever la db de secours, c'est pas pratique du tout

2020-11-01 15:17 UTC, Julien00859 commented
J'ai corrigé les problèmes, la liste de mes opérations est là https://docs.drlazor.be/noe.html

2020-11-01 15:22 UTC, Julien00859 commented
J'aime pas vraiment cet algorithme...

    max_views = float('+inf')
    if not forms.get('infinite_views'):
        try:
            max_views = float(forms.get('max_views', float('+inf')))
            if max_views < 1:
                raise bt.HTTPError(400, 'Max views should be greater than 0')                   # TODO: error handling in front-side
        except ValueError as e:
            raise bt.HTTPError(400, f"Max views '{forms.get('max_views')}' is not a number")    # TODO: error handling in front-side

Alors déjà pour les erreurs 400s, non il n'y a pas besoin de les gérer dans le frontend, il suffit de faire en sorte que le formulaire ne puisse pas envoyer de tels valeurs et c'est bon.

Alors ensuite on a déjà un traitement pour le formulaire juste au dessus là où on extrait le code et la langue, j'aimerais qu'on réutilise le code de ce côté plutôt que de refaire un bloc pour gérer les trucs.

Pour finir l'algo en lui-même est pas ouf, ce serait bien de définir des valeurs par défaut au départ (au même niveau que le `code=None`) qui seraient extraient de la configuration et non pas des valeurs magiques hardcodée (je parle pour le `float('inf')`).

2020-11-01 15:25 UTC, Julien00859 commented
> Je pense qu'il faudra enlever la db de secours, c'est pas pratique du tout

On peut faire ça dans un premier temps mais elle sera de toute manière de retour parce qu'on aura besoin de mocker la base de donnée redis dans les tests unitaires. Je comprend que tu ne veuilles pas t'occuper de ça, tu peux la virer pour le moment, je la remettrai quand j'attaquerai les tests.

2020-11-03 02:37 UTC, Julien00859 approved these changes

2020-11-03 02:37 UTC, Julien00859 commented
"enfin" :p

2020-11-03 02:37 UTC, merged