ref: move code highlight to python side
readthedocs-fr/bin-server pull request #42
Opened 2020-12-05 14:19 UTC by Julien00859

In order to implement a nice side-by-side highligted diff view we need
a diff library, the two file raw source code and extra abilities to
controle the generated html.

Using highlight.js proved to be too much cubersome as the python side
had to send the raw file and let javascript does everything, run a diff
algorithm, insert the new lines when needed, ensure the line numbering
is sync between the two files and highlight the source code.

As no JS dev took the challenge, this commit move all the highlighting
to python side. The library Pygments is a python library used by many
projects to hightlight source code. It is hackable and can produce HTML.

Related to #7
Related to #8

2020-12-05 14:51 UTC, NoeXWolf commented
Les tabulations ne sont du coup plus supportées.
Ça serait mieux aussi de mettre plus d'espace entre les lignes.
Et pour finir, je trouve que le thème n'est pas très joli, les couleurs sont trop saturées. J'ai regardé un peu tous les thèmes proposés et je trouve que **Tomorrow Night** / **Tomorrow Night Eighties** ou **Base16-ocean-dark** sont assez jolis, avec des couleurs plus pastels.

2020-12-05 14:55 UTC, AntoineJT commented
@NoeXWolf Les tabs seront toujours supportées, tout cela sera merge en temps voulu, donc les avancées ne sont pas perdues

2020-12-05 15:06 UTC, Julien00859 commented
Oui, l'historique de ma branche n'incorpore pas encore les derniers ajouts sur master. Je compte rebaser une fois proprement quand on aura réglé les détails.

Je note pour les thèmes d'ailleurs je suis assez d'accord, monokai c'est pas terrible dans le navigateur. On pourrait se faire une réunion où on passe en revu différents thèmes pour en choisir un qui fait l'unanimité. Pareil pour l'espacement entre les lignes.

Je mets un screenshot ci-dessous pour que tout le monde ne soit pas obligé de pull la branche pour voir le résultat final.

Ce qui m'intéresse surtout c'est de savoir si vous êtes OK pour changer highlight.js pour pygments :)

![screenshot](https://media.discordapp.net/attachments/743581334131310593/784781183933218886/2020-12-05_14-59-57.png?width=1439&height=625)

2020-12-05 15:13 UTC, NoeXWolf commented
Moi ça me va, je serai plus productif de ce côté là étant donné que le front j'y comprends rien...

2020-12-05 15:16 UTC, Julien00859 commented
By the way, voici la liste des thèmes disponibles:

    >>> from pygments.styles import get_all_styles
    >>> list(get_all_styles())
    ['default', 'emacs', 'friendly', 'colorful', 'autumn', 'murphy', 'manni', 'monokai', 'perldoc', 'pastie', 'borland', 'trac', 'native', 'fruity', 'bw', 'vim', 'vs', 'tango', 'rrt', 'xcode', 'igor', 'paraiso-light', 'paraiso-dark', 'lovelace', 'algol', 'algol_nu', 'arduino', 'rainbow_dash', 'abap', 'solarized-dark', 'solarized-light', 'sas', 'stata', 'stata-light', 'stata-dark', 'inkpot']

Et si tu veux jouer, tu peux aller là: https://pygments.org/demo/

2020-12-05 15:18 UTC, NoeXWolf commented
Ah mais c'est pas du tout les même que y'avait sur le site où j'étais...

2020-12-05 20:35 UTC, Aakodal requested changes

2020-12-05 20:35 UTC, Aakodal commented on bin/views/newform.html
> +            <select name="lang" selected="txt">option>
Un `option>` qui se ballade
```suggestion
            <select name="lang" selected="txt">
```

2020-12-05 20:35 UTC, Aakodal commented on bin/utils.py
> -    ('md', 'markdown'),
Un peu dommage d'avoir viré markdown

2020-12-05 20:35 UTC, Aakodal commented on bin/utils.py
> -    ('sh', 'bash'),
Je le mets sur bash (qui d'ailleurs a disparu alors que j'ai l'impression que pygments le supporte) mais ça s'adapte sur un peu tous les autres que tu as déplacés : pourquoi les avoir déplacés ? Ils étaient normalement triés par ordre alphabétique (plaintext exclu) afin justement qu'on s'embête pas à aller les chercher n'importe où

2020-12-08 23:33 UTC, KoukiFactori approved these changes

2020-12-09 20:09 UTC, Aakodal approved these changes

2020-12-12 16:45 UTC, NoeXWolf approved these changes

2020-12-23 19:31 UTC, merged