imp: anchors
readthedocs-fr/bin-server pull request #57
Opened 2020-12-28 13:09 UTC by Mesteery

Closes: #9.

Implémentation des ancres, avec une toute nouvelle structure pour le code, grâce au `table`. 

J'ai également refactor `monokai.css` (j'ai remplacer body par un sélecteur plus approprié, et j'ai enlevé des règles qui ne servaient a rien et qui jamais serviraient .
J'ai aussi utiliser `required` + `:valid` a la place du JS pour la validation du formulaire avec 1 ligne de JS, juste pour enlever le message d'erreur qui débordait de la page, et qui en plus servait a rien car, c'est déjà signalé par la couleur du bouton.

2020-12-28 13:15 UTC, AntoineJT commented
T'aurai pas du toucher à monokai.css car c'est un thème pygment.
Si un jour on veut changer de thème, il faudra qu'on aille modifier le nouveau thème pygment qui nous intéresse, conformément à tes modifications, et c'est pas quelque chose de souhaitable ça.

2020-12-28 13:18 UTC, Mesteery commented
Pas de soucis, le remet comme avant.

2020-12-28 14:47 UTC, Julien00859 requested changes

2020-12-28 14:47 UTC, Julien00859 commented on tests/test_controller.py
> -            self.testcase.assertIn('pre', self.stack)
Non, ceci n'est pas correct. On doit s'assurer que le code reste dans une balise \<pre\>\<code\> quite à n'avoir qu'une ligne. C'est pour des raisons de sécurité. Il y a une garanti du coté des navigateurs que le JS qui se trouve dans precode ne sera pas évalué.

2020-12-28 15:00 UTC, Mesteery commented on tests/test_controller.py
> -            self.testcase.assertIn('pre', self.stack)
Le code est systématiquement échappée par le `HtmlFormatter`. De plus, j'ai été obligé de mettre a jour les tests, car il n'y a plus aucun `pre-code` dans le code.

2020-12-28 15:22 UTC, Julien00859 commented on tests/test_controller.py
> -            self.testcase.assertIn('pre', self.stack)
Alors autant retirer le test complètement

2020-12-28 15:23 UTC, Julien00859 commented on tests/test_controller.py
> -            self.testcase.assertIn('pre', self.stack)
ou bien mieux, vérifier que le js est échapé

2020-12-28 15:48 UTC, Mesteery commented on tests/test_controller.py
> -            self.testcase.assertIn('pre', self.stack)
Je vois pas trop comment moi, je pourrais tester ca

2020-12-29 12:48 UTC, closed without merging

2020-12-29 13:22 UTC, Julien00859 commented
Moved to #58