add: submit snippets with ctrl+s
readthedocs-fr/bin-server pull request #79
Opened 2021-01-16 17:03 UTC by Linekio

Added ctrl+s shortcut to submit a snippet.
I have no idea for keyboards without Ctrl key.

2021-01-16 17:05 UTC, Mesteery requested changes

2021-01-16 17:05 UTC, Mesteery commented on bin/assets/scripts/newform-button.js
> +const form = document.forms[0]
```suggestion
const form = document.forms[0];
```

2021-01-16 17:05 UTC, Mesteery commented on bin/assets/scripts/newform-button.js
> +  }
ce n'est pas la ou il faut l'ajouter.

2021-01-16 17:10 UTC, Linekio commented on bin/assets/scripts/newform-button.js
> +  }
Pas là dans le code ou pas là dans l'html ?

2021-01-16 17:13 UTC, Mesteery commented on bin/assets/scripts/newform-button.js
> +  }
Il devrait etre dans un keydown listener sur le textarea

2021-01-16 17:15 UTC, Linekio commented on bin/assets/scripts/newform-button.js
> +  }
Bah justement, la variable code c'est le textarea : https://github.com/readthedocs-fr/bin/blob/main/bin/views/newform.html#L9

2021-01-16 17:17 UTC, Mesteery commented on bin/assets/scripts/newform-button.js
> +  }
Oui, mais c'est dans le mauvais listener.

2021-01-16 17:18 UTC, Mesteery commented on bin/assets/scripts/newform-button.js
> +  }
De plus, `keyCode` est dépréciée.

2021-01-16 17:18 UTC, Linekio commented on bin/assets/scripts/newform-button.js
> +  }
Bah non, c'est bien dans keydown x)

2021-01-16 17:22 UTC, Mesteery commented on bin/assets/scripts/newform-button.js
> +  }
Oui, oui, pardon, je me suis trompee avec GitHub, desolee

2021-01-16 17:40 UTC, Mesteery commented on bin/assets/scripts/newform-button.js
> +  }
```suggestion
  if (event.key === 's' && (navigator.platform.match('Mac') ? e.metaKey : e.ctrlKey))) {
    event.preventDefault();
    form.submit();
  }
```

2021-01-16 17:46 UTC, Julien00859 commented
N'oubliez pas de changer le message de commit (méthode squash + merge) pour renseigner l'issues que cette PR corrige :)

2021-01-31 15:24 UTC, Mesteery commented
@Linekio, j'ai un peu fais avancer les choses, si ca te dérange pas.

2021-01-31 15:28 UTC, Mesteery approved these changes

2021-01-31 16:19 UTC, Julien00859 commented
Je laisse l'auteur original donner son accord

2021-02-02 11:14 UTC, Linekio commented
Pas de soucis pour moi

2021-02-02 11:54 UTC, merged