Parent juc
readthedocs-fr/bin-server pull request #80
Opened 2021-01-18 22:39 UTC by Julien00859

imp: snippet edition and history
fix: always use byte-string redis keys
fix: rename "snippet_id" => "snippetid"
fix: load form code as utf-8

2021-01-18 22:41 UTC, Julien00859 commented
Les boutons sont dégueux et il faut encore écrire les tests unitaires, qui s'y colle ? (shotgun pas moi)

2021-01-19 06:49 UTC, Mesteery commented
> Les boutons sont dégueux et il faut encore écrire les tests unitaires, qui s'y colle ? (shotgun pas moi)

Je m'en occuperai

2021-01-22 18:46 UTC, NoeXWolf commented
C'est pas toi qui m'avait dit qu'il fallait jamais laisser un truc "à faire" sur une Pull Request ? :derp:

2021-01-22 19:09 UTC, NoeXWolf commented
Sinon, de mon côté je n'ai pas le bouton pour pouvoir faire une révision du snippet
![image](https://user-images.githubusercontent.com/39499143/105534380-b3e3fe00-5ced-11eb-9b2f-2bc3e0bdebeb.png)

2021-01-22 19:10 UTC, Mesteery commented
Si, il y est, mais il se voit peu.
Mais je suis en train de m'en occuper.

2021-01-22 19:12 UTC, NoeXWolf commented
Aussi petit bug mais pas très important, quand on clique sur "Voir le parent", ça amène sur `/<parentid>?`, avec le `?`.

2021-01-22 19:14 UTC, Mesteery commented
> Aussi petit bug mais pas très important, quand on clique sur "Voir le parent", ça amène sur `/<parentid>?`, avec le `?`.

Oui, c'est normal, étant donné qu'un form (methode GET) est utilisé, le navigateur met `?` pour l'url encoded.

2021-01-23 12:20 UTC, Mesteery commented
J'ai essayé de faire les tests unitaires mais j'ai pas réussi.

2021-01-23 16:11 UTC, Julien00859 commented on bin/controller.py
> +    snippet = models.Snippet.create(code, ext, max(maxusage, 0), lifetime, parentid)
Je suis contre qu'on sauvegarde le langage ou l'extension sur le modèle. Le modèle actuelle veut qu'on génère et partage des url avec une extension relative à la coloration syntaxique à privilégier. L'information est également présente dans le formulaire.

Selon moi, si tu veux forcer qu'une révision aie la même extension que son parent, tu retires le menu de sélection de la langue et tu rajoutes un `<input type=hidden name=lang value={{lang}}>` info que tu peux ajouter dans le formulaire.

2021-01-23 16:11 UTC, Julien00859 commented on bin/controller.py
> +            ext = models.Snippet.get_by_id(parentid).ext if parentid else parse_extension(forms.get('lang')) or ext
Trop compliqué, voir le commentaire ci-dessous, il est mieux de ne pas dupliquer la source de la langue

2021-01-23 16:11 UTC, Julien00859 commented on bin/views/newform.html
> +                % if not parentid:
Quid de si je veux faire une révision pour montrer une implémentation dans un autre langage ?

2021-01-23 16:13 UTC, Julien00859 commented on bin/models.py
> +    def __init__(self, ident, code, ext, views_left, parentid=''):
Quelle est cette atrocité ?

2021-01-23 16:13 UTC, Julien00859 commented on tests/test_controller.py
> +snippet_htmlxss = Snippet(ident='htmlxss', ext='html', code='<script>alert("XSS");</script>', views_left=float('+inf'))
cf plus haut

2021-01-23 16:27 UTC, Mesteery commented on bin/controller.py
> +    snippet = models.Snippet.create(code, ext, max(maxusage, 0), lifetime, parentid)
D'accord, mais d'ou viendrait `lang` ? Faut bien qu'il soit stocker quelque part

2021-01-23 16:28 UTC, Mesteery commented on bin/controller.py
> +    snippet = models.Snippet.create(code, ext, max(maxusage, 0), lifetime, parentid)
Ce que j'avais fait au début c'était de mettre le langage du parent comme langage par défaut sélectionnée.

2021-01-24 21:26 UTC, Mesteery requested changes

2021-01-24 21:26 UTC, Mesteery commented on bin/assets/scripts/newform.js
> +    const { value: content, selectionStart, selectionEnd } = code;
```suggestion
    const { value, selectionStart, selectionEnd } = code;
```
J'ai été con là dessus, il n'y aucun intérêt à renommer `value` en `content`.

2021-01-24 21:26 UTC, Mesteery commented on bin/assets/scripts/newform.js
> +    code.value = `${content.slice(0, selectionStart)}\t${content.slice(selectionEnd)}`;
```suggestion
    code.value = `${value.slice(0, selectionStart)}\t${value.slice(selectionEnd)}`;
```
*suite.*
(j'ai pas vu faire en une seule suggestion, vu que je suis sur téléphone.)

2021-01-30 07:51 UTC, Mesteery commented on bin/views/highlight.html
> +                <!-- missing icon -->
Que fait-on pour cette icône manquante ?

2021-01-30 14:15 UTC, Mesteery commented on bin/views/highlight.html
> +                </svg>
Je vois plus ca comme un "Copier", en tout cas ca fait très bizarre de se dire que ca représente un "Modifier"
![image](https://user-images.githubusercontent.com/48163546/106358668-e86b4180-630d-11eb-97e8-6b4af29366cc.png)

2021-01-30 14:22 UTC, Mesteery commented
![image](https://user-images.githubusercontent.com/48163546/106358846-f9688280-630e-11eb-8e2e-4d3340eccb12.png)

2021-01-30 14:26 UTC, fusetim commented on bin/views/highlight.html
> +                <!-- missing icon -->
C'est clairement un "Copier" comme tu l'as dit, ailleurs, je ne me vois pas l'utiliser pour voir la révision d'avant.
> Je vois plus ca comme un "Copier", en tout cas ca fait très bizarre de se dire que ca représente un "Modifier"

2021-01-30 14:28 UTC, Mesteery commented
> je ne me vois pas l'utiliser pour voir la révision d'avant.
Certes, mais l'icone reste plus approprié pour "Voir la revision precedente" que "Modifier"

2021-01-30 14:41 UTC, Julien00859 commented on bin/views/highlight.html
> +                </svg>
Normale... ça copie justement, je trouve l'icone actuelle parfaitement adaptée, celle permet de faire une copie modifiée

2021-01-30 14:43 UTC, Mesteery commented on bin/views/highlight.html
> +                </svg>
Ca me fait quand même bizarre

2021-01-30 14:43 UTC, Julien00859 commented
Pour l'icone snippet parent, je veux une flèche vers la gauche, mieux si c'est une flèche vers la gauche *dans* un document

2021-01-30 15:14 UTC, fusetim commented on bin/views/highlight.html
> +                <!-- missing icon -->
Quelque chose comme ça peut être ? 

![Frame 1(1)](https://user-images.githubusercontent.com/62183512/106359966-41d76e80-6316-11eb-8c0a-8161008d0a21.png)

```suggestion
                <svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
                    <path fill-rule="evenodd" clip-rule="evenodd" d="M4.58579 2.58579C4.96086 2.21071 5.46957 2 6 2H10.586C11.1164 2.00011 11.625 2.2109 12 2.586L15.414 6C15.7891 6.37499 15.9999 6.88361 16 7.414V16C16 16.5304 15.7893 17.0391 15.4142 17.4142C15.0391 17.7893 14.5304 18 14 18H6C5.46957 18 4.96086 17.7893 4.58579 17.4142C4.21071 17.0391 4 16.5304 4 16V4C4 3.46957 4.21071 2.96086 4.58579 2.58579ZM9.85571 7.29381C9.71506 7.15316 9.5243 7.07414 9.32538 7.07414C9.12647 7.07414 8.93571 7.15316 8.79505 7.29381C8.6544 7.43447 8.57538 7.62523 8.57538 7.82414V11.3241C8.57542 11.4739 8.6203 11.6203 8.70424 11.7443C8.78819 11.8684 8.90735 11.9644 9.04638 12.0201L11.5464 13.0201C11.7295 13.087 11.9315 13.08 12.1095 13.0005C12.2875 12.921 12.4276 12.7753 12.5 12.5943C12.5724 12.4133 12.5715 12.2112 12.4975 12.0308C12.4235 11.8505 12.2821 11.706 12.1034 11.6281L10.0754 10.8161V7.82414C10.0754 7.62523 9.99637 7.43447 9.85571 7.29381Z"/>
                </svg>
```

2021-01-30 15:32 UTC, Mesteery commented on bin/views/highlight.html
> +                <!-- missing icon -->
Ca a l'air magnifique, mais a mon avis, faudrait juste que "les flèches" soient plus "large", parce que ca fait un peu fin.
![image](https://user-images.githubusercontent.com/48163546/106360409-92e86200-6318-11eb-9c3f-3884929026e1.png)
Un peu comme la largeur du "plus", mais moins

2021-01-30 15:59 UTC, fusetim commented on bin/views/highlight.html
> +                <!-- missing icon -->
Quelque chose comme ça :

![Frame 4(1)](https://user-images.githubusercontent.com/62183512/106361118-8239eb00-631c-11eb-8008-eb49454ed9f3.png)


```suggestion
                <svg viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" fill="currentColor"><path d="M4.6 2.6C5 2.2 5.5 2 6 2H10.6C11.1 2 11.6 2.2 12 2.6L15.4 6C15.8 6.4 16 6.9 16 7.4V16C16 16.5 15.8 17 15.4 17.4 15 17.8 14.5 18 14 18H6C5.5 18 5 17.8 4.6 17.4 4.2 17 4 16.5 4 16V4C4 3.5 4.2 3 4.6 2.6ZM9.7 7.3C9.5 7.1 9.3 7 9 7 8.7 7 8.5 7.1 8.3 7.3 8.1 7.5 8 7.7 8 8V12.7C8 12.9 8.1 13.1 8.2 13.2 8.3 13.4 8.4 13.5 8.6 13.6L12 14.9C12.2 15 12.5 15 12.7 14.9 12.9 14.8 13.1 14.6 13.2 14.4 13.3 14.1 13.3 13.8 13.2 13.6 13.1 13.4 12.9 13.2 12.7 13.1L10 12V8C10 7.7 9.9 7.5 9.7 7.3Z"/></svg>
```

2021-01-31 07:12 UTC, Mesteery approved these changes
C'est parfait, mais il y a quelques petits problèmes d'indentation dans le HTML (autour des SVG je crois).

2021-01-31 14:24 UTC, fusetim approved these changes
C'est tout bon, éventuellement rajouter l'indentation manquante mais sinon tout marche. :+1:

2021-01-31 14:24 UTC, fusetim commented on bin/views/newform.html
> +                      <path fill-rule="evenodd" d="M6 2a2 2 0 00-2 2v12a2 2 0 002 2h8a2 2 0 002-2V7.414A2 2 0 0015.414 6L12 2.586A2 2 0 0010.586 2H6zm5 6a1 1 0 10-2 0v3.586l-1.293-1.293a1 1 0 10-1.41
```suggestion
                        <path fill-rule="evenodd" d="M6 2a2 2 0 00-2 2v12a2 2 0 002 2h8a2 2 0 002-2V7.414A2 2 0 0015.414 6L12 2.586A2 2 0 0010.586 2H6zm5 6a1 1 0 10-2 0v3.586l-1.293-1.293a1 1 0 10-1.414 1.414l3 3a1 1 0 001.414 0l3-3a1 1 0 00-1.414-1.414L11 11.586V8z" clip-rule="evenodd" />
```

2021-01-31 14:27 UTC, Mesteery commented on bin/views/highlight.html
> +                </svg>
```suggestion
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M9 2a2 2 0 00-2 2v8a2 2 0 002 2h6a2 2 0 002-2V6.414A2 2 0 0016.414 5L14 2.586A2 2 0 0012.586 2H9z" />
                    <path d="M3 8a2 2 0 012-2v10h8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z" />
                </svg>
            </a>
            <a class="control" title="Nouveau" href="/">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M6 2a2 2 0 00-2 2v12a2 2 0 002 2h8a2 2 0 002-2V7.414A2 2 0 0015.414 6L12 2.586A2 2 0 0010.586 2H6zm5 6a1 1 0 10-2 0v2H7a1 1 0 100 2h2v2a1 1 0 102 0v-2h2a1 1 0 100-2h-2V8z" clip-rule="evenodd" />
                </svg>
```

2021-01-31 15:10 UTC, merged