fix: form buttons were sticking in place
readthedocs-fr/bin-server pull request #97
Opened 2021-02-12 16:46 UTC by Julien00859

Save a pretty long code snippet, long enough you need to scroll the page
to see it entirely. When you scroll down, the few buttons (duplicate, new,
previous revision) don't stay in the bottom left corner but instead scroll
too. They should stick on the bottom right corner.

Closes #95
Closes #96

2021-02-12 20:14 UTC, fusetim commented
Certes, les boutons restent sur le bord droit inférieur, mais je ne pense pas que cela règle le problème pour autant.

https://user-images.githubusercontent.com/62183512/107817891-0a85aa80-6d77-11eb-96a3-fa046719ff76.mp4

2021-02-12 20:15 UTC, Mesteery commented
Ça c'est un autre problème (c.f. #77)

2021-02-12 20:17 UTC, fusetim commented
> Ça c'est un autre problème (c.f. #77)

ah c'était pas très clair pour moi

2021-02-13 10:17 UTC, AntoineJT approved these changes
Je viens de le tester de mon côté, fonctionne comme prévu

2021-02-13 14:49 UTC, Mesteery commented
Désolé si je vous retarde, mais j'ai un petit doute sur la suppression du `left` et autres choses, je teste dès ce soir et je vous dis.

2021-02-13 14:55 UTC, AntoineJT commented
Le `left: 0` n'a rien à faire ici afaik. ça n'aurait pas vraiment de sens de mettre ça, étant donné qu'on veut cadrer les boutons en bas à droite. 
Le `position: fixed` permet de les positionner aux coordonnées spécifiés par `left`, `right`, `top`, `bottom` et le `padding` permet de laisser de l'espace pour ne pas les coller au bord.
Je peux bien évidemment me tromper, mais de ce que je sais, voici l'explication à ces changements.

2021-02-13 14:57 UTC, Mesteery commented
Le `left` était là pour que le parent de ces boutons prennent l'entièreté de la largeur.

2021-02-13 15:01 UTC, AntoineJT requested changes
Okay, du coup on attend la review de Mestery avant de merge (je lock avec un `request changes`, vu que j'ai pas trouvé de moyen plus adapté de le faire)

2021-02-13 15:30 UTC, Mesteery commented
Si tu veux tu peux laisser ton approve et j'ajoute mon request change, pour éviter une confusion

2021-02-13 15:30 UTC, Mesteery approved these changes

2021-02-13 15:31 UTC, Mesteery requested changes
Je regarde ça ce soir.

2021-02-13 15:31 UTC, AntoineJT approved these changes

2021-02-13 22:02 UTC, Mesteery approved these changes
Je viens de tester, c'est bon.
Par contre, sur un écran de petite taille, c'est pire, les boutons sont du coup tout en bas a gauche de la page et ne suivent pas le scroll (#77).
Malgré ca, ceci devrait être merge et fixé par une autre PR.

2021-02-13 23:14 UTC, merged

2021-02-13 23:15 UTC, Julien00859 commented
Pour les écrans de petite taille on doit avoir une réflexion plus importante niveau design, ya pas mal de trucs qui sont pas génial